resume:
  ckpt_path: False

trainer:
  exp_dir: "./exp/CartPole-v1"
  lr: 0.001

train:
  iters_n: 10000
  log_freq: 2
  save_freq: 10000
  local_steps: &local_steps 8
  steps_n: 5

net:
  in_channels: 4 # S-size
  out_channels: 2 # A-size
  inner_channels: 16
  layers_n: 5

env:
  env_name: "CartPole-v1"
  num_envs: 2

algo:
  T: *local_steps
  gamma: 0.99
  lam: 0.95
  epsilon: 0.1
  v_loss_weight: 1
  e_loss_weight: 0.001
