resume:
  ckpt_path: False

trainer:
  exp_dir: "./exp/LunarLander-v2"
  lr: 0.001

train:
  iters_n: 50000
  log_freq: 2
  save_freq: 10000
  local_steps: &local_steps 16
  steps_n: 15

net:
  in_channels: 8 # S-size
  out_channels: 4 # A-size
  inner_channels: 128
  layers_n: 5

env:
  env_name: "LunarLander-v2"
  num_envs: 64

algo:
  T: *local_steps
  gamma: 0.99
  lam: 0.95
  epsilon: 0.1
  v_loss_weight: 1
  e_loss_weight: 0.05
